(function(){
  const API=window.TEENLAUNCH_API_BASE,token=localStorage.getItem("teenlaunch_token");
  if(!token){location.replace(`auth.html?mode=login&returnTo=${encodeURIComponent("career-copilot.html")}`);return}
  const storageKey="teenlaunch_career_copilot_session",messagesRoot=document.querySelector("[data-chat-messages]"),form=document.querySelector("[data-chat-form]"),loading=document.querySelector("[data-chat-loading]"),errorBox=document.querySelector("[data-chat-error]");
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  let messages=[];try{messages=JSON.parse(sessionStorage.getItem(storageKey)||"[]").filter(m=>["user","assistant"].includes(m.role)).slice(-20)}catch{messages=[]}
  if(!messages.length)messages=[{role:"assistant",content:"Hi! I’m your TeenLaunch Career Copilot. I can help you understand your Career DNA, explore skills and find suitable verified TeenLaunch opportunities.",source:"database"}];
  const save=()=>sessionStorage.setItem(storageKey,JSON.stringify(messages.slice(-20)));
  const render=()=>{messagesRoot.innerHTML=messages.map(message=>`<article class="copilot-bubble ${message.role}">${esc(message.content)}${message.role==="assistant"?`<small class="response-source">${message.source==="ai"?"AI-generated using your minimal TeenLaunch career context.":message.source==="database_fallback"?"Database-based fallback guidance.":"TeenLaunch guidance."}</small>${message.opportunities?.length?`<div class="opportunity-references">${message.opportunities.map(o=>`<a href="${esc(o.link.replace(/^pages\//,""))}">${esc(o.title)}</a>`).join("")}</div>`:""}`:""}</article>`).join("");messagesRoot.scrollTop=messagesRoot.scrollHeight};
  const send=async text=>{const question=String(text||"").trim();if(!question)return;errorBox.hidden=true;messages.push({role:"user",content:question});render();save();form.elements.message.value="";form.querySelector("button").disabled=true;loading.hidden=false;try{const history=messages.slice(0,-1).slice(-8).map(({role,content})=>({role,content}));const response=await fetch(`${API}/career-copilot/chat`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({message:question,history})});if(response.status===401||response.status===403){location.replace(`auth.html?mode=login&returnTo=${encodeURIComponent("career-copilot.html")}`);return}if(!response.ok){let text="Career Copilot could not respond.";try{text=(await response.json()).error?.message||text}catch{}throw new Error(text)}const data=await response.json();messages.push({role:"assistant",content:data.answer,source:data.source,opportunities:data.opportunities||[]});save();render()}catch(error){errorBox.textContent=error.message;errorBox.hidden=false}finally{loading.hidden=true;form.querySelector("button").disabled=false;form.elements.message.focus()}};
  form.addEventListener("submit",event=>{event.preventDefault();send(form.elements.message.value)});document.querySelectorAll("[data-starter]").forEach(button=>button.addEventListener("click",()=>send(button.textContent)));document.querySelector("[data-clear-chat]").addEventListener("click",()=>{messages=[];sessionStorage.removeItem(storageKey);messages.push({role:"assistant",content:"Conversation cleared. What career goal would you like to explore?",source:"database"});render()});render();
})();
