(function(){
  const API=window.TEENLAUNCH_API_BASE,token=localStorage.getItem("teenlaunch_token"),id=new URLSearchParams(location.search).get("id"),H={Authorization:`Bearer ${token}`};
  if(!token){location.replace(`auth.html?mode=login&returnTo=${encodeURIComponent(location.pathname+location.search)}`);return}
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const card=item=>{const o=item.opportunities||{};return `<article class="application-card">${o.image_url?`<img src="${esc(o.image_url)}" alt="">`:""}<h3>${esc(o.title||"Opportunity")}</h3><p>${esc(o.category||"")}</p><p>${esc(o.organizer||"")}</p><p>Deadline: ${o.deadline?new Date(o.deadline+"T00:00:00").toLocaleDateString():"Rolling"}</p><a class="btn secondary" href="opportunity-details.html?id=${encodeURIComponent(item.opportunity_id)}">View Details</a></article>`};
  const fail=message=>{document.querySelector("[data-member-loading]").hidden=true;document.querySelector("[data-member-error]").hidden=false;document.querySelector("[data-member-error-message]").textContent=message};
  const load=async()=>{if(!id){fail("Missing member ID.");return}const r=await fetch(`${API}/social/users/${encodeURIComponent(id)}/profile`,{headers:H});if(!r.ok){let m="Profile could not be loaded.";try{m=(await r.json()).error?.message||m}catch{}fail(m);return}const d=await r.json(),p=d.profile||{},pic=p.profile_picture_url||p.avatar_url;
    document.querySelector("[data-member-username]").textContent=`@${p.username||"teenlaunch-user"}`;document.querySelector("[data-member-name]").textContent=p.full_name||"TeenLaunch user";document.querySelector("[data-member-bio]").textContent=p.bio||"No bio yet.";document.querySelector("[data-member-school]").textContent=p.school_name||"";document.querySelector("[data-member-initials]").textContent=(p.full_name||"TL").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();if(pic)document.querySelector("[data-member-picture]").src=pic;
    [["app-count",d.counts.applications],["followers",d.counts.followers],["following",d.counts.following]].forEach(([k,v])=>document.querySelector(`[data-member-${k}]`).textContent=v||0);document.querySelector("[data-member-followers-link]").href=`connections.html?user=${encodeURIComponent(id)}&type=followers`;document.querySelector("[data-member-following-link]").href=`connections.html?user=${encodeURIComponent(id)}&type=following`;
    document.querySelector("[data-about-name]").textContent=p.full_name||"-";document.querySelector("[data-about-bio]").textContent=p.bio||"-";document.querySelector("[data-about-school]").textContent=p.school_name||"-";document.querySelector("[data-member-applications]").innerHTML=d.applications.map(card).join("");document.querySelector("[data-member-saved]").innerHTML=d.saved.map(card).join("");document.querySelector("[data-member-app-empty]").hidden=d.applications.length>0;document.querySelector("[data-member-saved-empty]").hidden=d.saved.length>0;
    const follow=document.querySelector("[data-member-follow]");follow.dataset.following=String(d.following);follow.textContent=d.following?"Following":"Follow";follow.hidden=d.own_profile;document.querySelector("[data-member-message]").href=`inbox.html?user=${encodeURIComponent(id)}`;document.querySelector("[data-member-message]").hidden=d.own_profile;follow.addEventListener("click",async()=>{const on=follow.dataset.following==="true";follow.disabled=true;const response=await fetch(`${API}/social/follows/${encodeURIComponent(id)}`,{method:on?"DELETE":"POST",headers:H});if(response.ok||response.status===409){follow.dataset.following=String(!on);follow.textContent=!on?"Following":"Follow"}follow.disabled=false});
    document.querySelector("[data-member-loading]").hidden=true;document.querySelector("[data-member-content]").hidden=false};
  document.querySelectorAll("[data-member-tab]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-member-tab]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll("[data-member-panel]").forEach(x=>x.hidden=x.dataset.memberPanel!==b.dataset.memberTab)}));load();
})();
