(function(){
  const API=window.TEENLAUNCH_API_BASE,token=localStorage.getItem("teenlaunch_token"),H={Authorization:`Bearer ${token}`};
  if(!token){location.replace("auth.html?mode=login&returnTo=portfolio-builder.html");return}
  let state={};const message=document.querySelector("[data-builder-message]"),t=key=>window.TeenLaunchI18n?.translate(key)||key,isChinese=()=>window.TeenLaunchI18n?.getLanguage()==="zh";
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const request=async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{...H,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});if(!r.ok){let text="Request failed";try{text=(await r.json()).error?.message||text}catch{}throw new Error(text)}return r.status===204?null:r.json()};
  const notify=(text,type="")=>{const content=text?t(text):"";message.textContent=content;message.className=`portfolio-message ${type}`;message.hidden=!content};
  const official=a=>`<span class="verified-badge">✓ ${esc(t(a.completion_badge||"Verified"))}</span><h3>${esc(a.opportunities?.title||t("Completed programme"))}</h3><p><strong>${esc(a.opportunities?.organizer||t("Organisation"))}</strong></p><p>${t("Completed")} ${a.completion_date?new Date(a.completion_date+"T00:00:00").toLocaleDateString(isChinese()?"zh-CN":undefined):t("date not provided")}</p><div class="skill-list">${(a.verified_skills||[]).map(s=>`<span class="skill-chip">${esc(t(s))}</span>`).join("")}</div>${a.admin_remarks?`<p>${esc(a.admin_remarks)}</p>`:""}${a.certificate_url?`<a class="certificate-link" href="${esc(a.certificate_url)}" target="_blank" rel="noopener">${t("View certificate")}</a>`:""}`;
  const render=()=>{
    const added=new Set(state.items.map(i=>i.registration_id));
    const available=state.verified_achievements.filter(a=>!added.has(a.id));
    document.querySelector("[data-verified-list]").innerHTML=available.map(a=>`<article class="verified-card">${official(a)}<button class="btn primary" data-add-achievement="${a.id}" type="button">Add to portfolio</button></article>`).join("");document.querySelector("[data-verified-empty]").hidden=available.length>0;
    document.querySelector("[data-item-list]").innerHTML=state.items.map((item,index)=>`<article class="portfolio-item-editor" data-item="${item.id}"><header><div>${official(item.registrations)}</div><div class="editor-actions"><button type="button" class="btn secondary" data-move="-1" ${index===0?"disabled":""}>↑</button><button type="button" class="btn secondary" data-move="1" ${index===state.items.length-1?"disabled":""}>↓</button><button type="button" class="btn secondary" data-remove-item>Remove</button></div></header><p class="locked-note">Programme, organisation, verification and completion details are locked.</p><form data-item-form><label>Personal description<textarea name="user_description" rows="3">${esc(item.user_description||"")}</textarea></label><label>Reflection<textarea name="reflection" rows="4">${esc(item.reflection||"")}</textarea></label><button class="btn secondary" type="button" data-improve>Format with writing template</button><small data-helper-notice></small><label>Skills learned<input name="skills_learned" value="${esc((item.skills_learned||[]).join(", "))}" placeholder="Teamwork, Public speaking"></label><label>Project images or evidence URLs<input name="evidence_urls" value="${esc((item.evidence_urls||[]).join(", "))}" placeholder="https://… separated by commas"></label><label class="portfolio-check"><input name="is_published" type="checkbox" ${item.is_published?"checked":""}> Show on public portfolio</label><button class="btn primary" type="submit">Save achievement</button></form></article>`).join("");document.querySelector("[data-items-empty]").hidden=state.items.length>0;
    document.querySelector("[data-project-list]").innerHTML=state.projects.map(p=>projectEditor(p)).join("");document.querySelector("[data-projects-empty]").hidden=state.projects.length>0;bind();
  };
  const projectEditor=p=>`<article class="portfolio-project-editor" data-project="${p.id}"><form data-project-form><label>Project title<input name="title" required value="${esc(p.title||"")}"></label><label>Description<textarea name="description" rows="4">${esc(p.description||"")}</textarea></label><button class="btn secondary" type="button" data-improve-project>Format with writing template</button><small data-helper-notice></small><label>Skills<input name="skills" value="${esc((p.skills||[]).join(", "))}"></label><label>Evidence URLs<input name="evidence_urls" value="${esc((p.evidence_urls||[]).join(", "))}"></label><label class="portfolio-check"><input name="is_published" type="checkbox" ${p.is_published?"checked":""}> Show publicly</label><div class="editor-actions"><button class="btn primary" type="submit">Save project</button><button class="btn secondary" type="button" data-delete-project>Delete</button></div></form></article>`;
  const formPayload=form=>{const d=Object.fromEntries(new FormData(form));return{...d,is_published:form.elements.is_published.checked,skills_learned:d.skills_learned?.split(","),skills:d.skills?.split(","),evidence_urls:d.evidence_urls?.split(",")}};
  const improve=async(textarea,notice)=>{const d=await request("/portfolio/writing-helper",{method:"POST",body:JSON.stringify({text:textarea.value})});textarea.value=d.text;notice.textContent=d.notice};
  const bind=()=>{
    document.querySelectorAll("[data-add-achievement]").forEach(b=>b.onclick=async()=>{await request("/portfolio/items",{method:"POST",body:JSON.stringify({registration_id:b.dataset.addAchievement,position:state.items.length})});await load();notify("Achievement added.","success")});
    document.querySelectorAll("[data-item-form]").forEach(form=>{const root=form.closest("[data-item]");form.onsubmit=async e=>{e.preventDefault();await request(`/portfolio/items/${root.dataset.item}`,{method:"PUT",body:JSON.stringify(formPayload(form))});notify("Achievement saved.","success");await load()};root.querySelector("[data-remove-item]").onclick=async()=>{await request(`/portfolio/items/${root.dataset.item}`,{method:"DELETE"});await load()};root.querySelectorAll("[data-move]").forEach(b=>b.onclick=async()=>{const i=state.items.findIndex(x=>x.id===root.dataset.item),j=i+Number(b.dataset.move);if(j<0||j>=state.items.length)return;await Promise.all([request(`/portfolio/items/${state.items[i].id}`,{method:"PUT",body:JSON.stringify({position:j})}),request(`/portfolio/items/${state.items[j].id}`,{method:"PUT",body:JSON.stringify({position:i})})]);await load()});root.querySelector("[data-improve]").onclick=()=>improve(form.elements.reflection,root.querySelector("[data-helper-notice]")).catch(e=>notify(e.message,"error"))});
    document.querySelectorAll("[data-project-form]").forEach(form=>{const root=form.closest("[data-project]");form.onsubmit=async e=>{e.preventDefault();await request(`/portfolio/projects/${root.dataset.project}`,{method:"PUT",body:JSON.stringify(formPayload(form))});notify("Project saved.","success");await load()};root.querySelector("[data-delete-project]").onclick=async()=>{await request(`/portfolio/projects/${root.dataset.project}`,{method:"DELETE"});await load()};root.querySelector("[data-improve-project]").onclick=()=>improve(form.elements.description,root.querySelector("[data-helper-notice]")).catch(e=>notify(e.message,"error"))});
  };
  const publicUrl=()=>new URL(`public-portfolio.html?slug=${encodeURIComponent(state.portfolio.slug)}`,location.href).href;
  const copyText=async text=>{if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return true}catch(error){}}const field=document.createElement("textarea");field.value=text;field.setAttribute("readonly","");field.style.position="fixed";field.style.opacity="0";document.body.appendChild(field);field.select();field.setSelectionRange(0,field.value.length);const copied=document.execCommand("copy");field.remove();return copied};
  window.copyTeenLaunchPortfolioLink=event=>{event?.preventDefault();event?.stopImmediatePropagation();if(!state.portfolio?.is_public){notify("Make the portfolio public first.","error");return false}copyText(publicUrl()).then(copied=>notify(copied?"Public link copied.":"Copying was blocked by the browser. Use the visible public link instead.",copied?"success":"error"));return false};
  const renderPublicLink=()=>{const row=document.querySelector("[data-public-link-row]"),link=document.querySelector("[data-public-link]");const visible=Boolean(state.portfolio?.is_public&&state.portfolio?.slug);row.hidden=!visible;if(!visible)return;link.href=publicUrl();link.textContent=publicUrl()};
  const load=async()=>{try{state=await request("/portfolio/me");const f=document.querySelector("[data-profile-form]"),p=state.portfolio;f.elements.introduction.value=p.introduction||"";f.elements.personal_description.value=p.personal_description||"";f.elements.slug.value=p.slug||"";f.elements.contact.value=p.contact_links?.contact||"";f.elements.social.value=p.contact_links?.social||"";f.elements.is_public.checked=p.is_public;document.querySelector("[data-builder-content]").hidden=false;renderPublicLink();notify("");render()}catch(e){notify(e.message,"error")}};
  document.querySelector("[data-profile-form]").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await request("/portfolio/profile",{method:"PUT",body:JSON.stringify({introduction:f.elements.introduction.value,personal_description:f.elements.personal_description.value,slug:f.elements.slug.value,is_public:f.elements.is_public.checked,contact_links:{contact:f.elements.contact.value,social:f.elements.social.value}})});notify("Portfolio settings saved.","success");await load()}catch(err){notify(err.message,"error")}};
  const newProjectButton=document.querySelector("[data-new-project]");
  let creatingProject=false;
  newProjectButton.onclick=async()=>{
    if(creatingProject)return;
    creatingProject=true;
    newProjectButton.disabled=true;
    newProjectButton.setAttribute("aria-busy","true");
    const originalText=newProjectButton.textContent;
    newProjectButton.textContent="Adding...";
    try{
      await request("/portfolio/projects",{method:"POST",body:JSON.stringify({title:"New project",position:state.projects.length})});
      await load();
      notify("New project added.","success");
    }catch(e){
      notify(e.message,"error");
    }finally{
      creatingProject=false;
      newProjectButton.disabled=false;
      newProjectButton.removeAttribute("aria-busy");
      newProjectButton.textContent=originalText;
    }
  };
  document.querySelector("[data-copy-link]").addEventListener("click",window.copyTeenLaunchPortfolioLink,{capture:true});load();
})();
